config/routes.rb
Recyclo::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
  root 'welcome#index'

  get 'activity' => 'dashboard#index', as: 'user_activity'
  get 'profiles/:id' => 'users#show', as: 'user_profile'
  
  get "participa/donando" => 'welcome#giver'
  get "participa/recolectando" => 'welcome#picker'
  
  resources :offers
  put "offers/:id/toggle" => "offers#toggle_visibility", as: 'toggle_offer_visibility'
  resources :users
  resources :deposits
  resources :appointments
  resources :messages
  resources :proposals
  
  get 'aviso-de-privacidad' => 'welcome#privacy_note', as: 'privacy_note'
  get 'admin' => 'admin#index'

end

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/assets/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/assets/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/assets/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/assets/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/assets/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/assets/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/assets/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/assets/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/assets/favicons/favicon-194x194.png" sizes="194x194">
<link rel="icon" type="image/png" href="/assets/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/assets/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/assets/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/assets/favicons/images/manifest.json">
<meta name="msapplication-TileColor" content="#00a300">
<meta name="msapplication-TileImage" content="/assets/favicons/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_messages.html.erb
<% if !flash[:notice].blank? || content_for?(:notice) %>
<div class="alert-container">
	<div class="alert alert-dismissible alert-success">
		<button class="close" data-dismiss="alert" type="button">×</button>
		<p class="centered"><%= flash[:notice]  || yield(:notice).html_safe %></p>
	</div>
</div>
<% end %>

<% if !flash[:warning].blank? || content_for?(:warning) %>
<div class="alert-container">
	<div class="alert alert-dismissible alert-warning">
		<button class="close" data-dismiss="alert" type="button">×</button>
		<p class="centered"><%= flash[:warning] || yield(:warning).html_safe %></p>
	</div>
</div>
<% end %>

<% if !flash[:error].blank?  || content_for?(:error) %>
<div class="alert-container">
	<div class="alert alert-dismissible alert-danger">
		<button class="close" data-dismiss="alert" type="button">×</button>
		<p class="centered"><%= flash[:error] || yield(:error).html_safe %></p>
	</div>
</div>
<% end %>

app/views/shared/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("6ed8f50df13793758a40ecd485dd688e");</script><!-- end Mixpanel -->

<!-- Get the user's IP -->
<script type="text/javascript" src="http://l2.io/ip.js?var=userip"></script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">
			<%= image_tag('logo-mini.png') %>
		</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<% if current_user.is_a_giver? %>
						<li>
							<a href="<%= new_offer_path %>">
								<b><span class='glyphicon glyphicon-plus' aria-hidden="true"></span> Publicar reciclable</b>
							</a>
						</li>
						<% elsif current_user.is_a_picker? %>
						<li>
							<a href="<%= offers_path %>">
								<b><span class='glyphicon glyphicon-list' aria-hidden="true"></span> Buscar reciclables</b>
							</a>
						</li>
						<li>
							<a href="<%= deposits_path %>">
								<b><span class='glyphicon glyphicon-leaf' aria-hidden="true"></span></b> Centros de acopio
							</a>
						</li>
					<% end %>
				<% end %>
      </ul>
			
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
          <% if current_user.is_a_picker? %>
      		  <li><a href="<%= user_activity_path %>"><b>Reciclables en observación</b></a></li>
          <% else %>
      		  <li><a href="<%= user_activity_path %>"><b>Mis reciclables publicados</b></a></li>
          <% end %>
        	<li><a href="<%= user_profile_path(current_user.id) %>"><span class='glyphicon glyphicon-user' aria-hidden="true"></span>&nbsp;&nbsp;Hola <b><%= current_user.full_name.split(' ').first %>!</b></a></li>
					<li><a href="<%= destroy_user_session_path %>">Salir</a></li>
				<% else %>
        	<li><a href="<%= new_user_session_path %>">Ingresar</a></li>
				<% end %>
      </ul>
    </div>
  </div>
</div>