config/routes.rb
Recyclo::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
  root 'welcome#index'

  get 'activity' => 'dashboard#index', as: 'user_activity'
  get 'profiles/:id' => 'users#show', as: 'user_profile'
  
  get "participa/donando" => 'welcome#giver'
  get "participa/recolectando" => 'welcome#picker'
  
  resources :offers
  put "offers/:id/toggle" => "offers#toggle_visibility", as: 'toggle_offer_visibility'
  resources :users
  resources :deposits
  resources :appointments
  resources :messages
  resources :proposals
  
  get 'aviso-de-privacidad' => 'welcome#privacy_note', as: 'privacy_note'
  get 'admin' => 'admin#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    Tracker.track_event(request.ip, 'Visited index')
    redirect_to(user_activity_path) if user_signed_in?
  end
  
  def picker
    Tracker.track_event(request.ip, 'User as picker')
    session[:user_kind] = User.roles[:picker]
    redirect_to offers_path
  end
  
  def giver
    Tracker.track_event(request.ip, 'User as giver')
    session[:user_kind] = User.roles[:giver]
    redirect_to new_offer_path
  end
  
  def privacy_note
     render layout: 'front' 
  end
end

app/helpers/welcome_helper.rb
#encoding: utf-8
module WelcomeHelper
  
  def localized_material(kind)
    if kind.eql?('PET')
      "plástico"
    elsif kind.eql?('paper')
      "papel"
    elsif kind.eql?('metal')
      "metal"
    elsif kind.eql?('glass')
      "vidrio"
    end
  end
end

app/views/welcome/index.html.erb
<div id="landing-page" class="lp">
  <div class="left-floating-navbar">
    <ul>
      <li><b>Síguenos en:</b></li>
    	<li>
        <%= link_to image_tag('twitter_icon.png', size: '25x25'), 'http://twitter.com/recyclomx', target: '_blank' %>
      </li>
    	<li>
        <%= link_to image_tag('facebook_icon.png', size: '25x25'), 'https://www.facebook.com/recyclo.mx', target: '_blank' %>
      </li>
    </ul>
  </div>
	<div class="floating-navbar">
    <ul>
    	<li>
        <%= link_to "<i class='glyphicon glyphicon-user'></i>&nbsp;&nbsp;Ingresar".html_safe, new_user_session_path %>
      </li>
      <li>
    	  <%= link_to "<i class='glyphicon glyphicon-pencil'></i>&nbsp;&nbsp;&nbsp;Regístrate".html_safe, new_user_registration_path %>
      </li>
    </ul>
	</div>
	<div id="slides">
	  <div class="slides-container">
			<%= render partial: 'welcome/slides/slide', locals: {kind: 'metal'} %>
			<%= render partial: 'welcome/slides/slide', locals: {kind: 'glass'} %>
			<%= render partial: 'welcome/slides/slide', locals: {kind: 'paper'} %>
			<%= render partial: 'welcome/slides/slide', locals: {kind: 'PET'} %>
	  </div>
	</div>
  
  <div class="fixed-container">
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-4 col-lg-offset-4 centered header">
            <%= image_tag('logo.png', class: 'img-responsive centered-in') %>
            <p class="slogan">Comercializa reciclables fácil y rápido con personas cerca de ti, mejorando tu ciudad</p>
            
            <span class="know-more">
              <a href="javascript:void(0)" class="btn btn-lg btn-primary show-more-info" id="how-it-works">¿Cómo funciona?</a>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="start-opts">
      <div class"row">
        <div class="col-lg-1"></div>
        <a href="<%= participa_donando_path %>" class="col-lg-1">
          <%= image_tag("recyclable-metal.png", class: 'img-responsive centered-in') %>
        </a>
        <a href="<%= participa_donando_path %>" class="col-lg-3">
          <h4 class="title">Dona tus reciclables</h4>
          <p class="text">Almacena, publica y dona reciclables generando un cambio positivo.</p>
        </a>
        <div class="col-lg-2"></div>
        <a href="<%= participa_recolectando_path %>" class="col-lg-3 right">
          <h4 class="title">Recolecta reciclables</h4>
          <p class="text">Busca, recolecta y vende reciclables en depósitos cercanos a tu ubicación.</p>
        </a>
        <a href="<%= participa_recolectando_path %>" class="col-lg-1">
          <%= image_tag("recyclable-metal-pay.png", class: 'img-responsive centered-in') %>
        </a>
        <div class="col-lg-1"></div>
      </div>
    </div>
		<div class="footer centered">
			<ul>
				<li class="privacy text">
          <%= link_to 'Aviso de privacidad', privacy_note_path,  target: '_blank' %>
        </li>
        <li class="privacy text"><b>Recyclo 2015</b></li>
			  <% if false %>
        <li class="social-nets">
          <%= link_to image_tag('twitter_icon.png', class: 'preserve icon') %>
          <%= link_to image_tag('facebook_icon.png', class: 'preserve icon') %>
        </li>
        <% end %>
				<li class="privacy text">Contáctanos en <i><%= mail_to('contacto@recyclo.mx') %></i></li>
			</ul>
		</div>
	</div>
  
  <div class="fixed-modal">
    <%= link_to image_tag('close-icon.png', size: '30x30'), 'javascript:void(0)', class: 'fixed-icon  hide-more-info', id: 'close-how-it-works' %>
    <div class="contents-of-modal">
      <div class"row">
        <div class="col-lg-5 steps">
          <%= image_tag('world-icon.png', size: '500x500', class: 'fixed-left-icon') %>
          <h4 class="centered title">Donar reciclables</h4>
          
          <div class="step row">
            <div class="col-lg-2 number">1</div>
            <div class="col-lg-10 instruction">
              <p><b>Separa</b> tu basura y almacena reciclables como el vidrio, cartón, plásticos, metal o fierros.</p>
            </div>
          </div>
          <div class="step row">
            <div class="col-lg-2 number">2</div>
            <div class="col-lg-10 instruction">
              <p><b>Publica</b> el tipo y la cantidad de reciclables que vas a donar.</p>
            </div>
          </div>
          <div class="step row">
            <div class="col-lg-2 number">3</div>
            <div class="col-lg-10 instruction">
              <p><b>Acuerda</b> una fecha y hora con el recolector que tu selecciones a través de <i>Recyclo</i> para entregarle los reciclables.</p>
            </div>
          </div>
          <div class="step row conclusive">
            <div class="col-lg-12 centered">
              <p class="button">
                <%= link_to 'Empieza a donar', participa_donando_path, class: 'btn btn-primary btn-primary-lg' %>
              </p>
              <p class="mini-title">y ayuda al planeta!</p>
            </div>
          </div>
        </div>
        <div class="col-lg-2"></div>
        <div class="col-lg-5 steps">
          <%= image_tag('money-icon.png', size: '500x500', class: 'fixed-right-icon') %>
          <h4 class="centered title">Hacer dinero recolectando reciclables</h4>
          
          <div class="step row">
            <div class="col-lg-2 number">1</div>
            <div class="col-lg-10 instruction">
              <p><b>Busca</b> reciclables cercanos a tu ubicación.</p>
            </div>
          </div>
          <div class="step row">
            <div class="col-lg-2 number">2</div>
            <div class="col-lg-10 instruction">
              <p><b>Contacta</b> al donador a través de <i>Recyclo</i> para acordar fecha y hora para recogerlos.</p>
            </div>
          </div>
          <div class="step row">
            <div class="col-lg-2 number">3</div>
            <div class="col-lg-10 instruction">
              <p><b>Recoge</b> los reciclables, llévalos al centro de acopio más cercano y recibe dinero por ellos.</p>
            </div>
          </div>
          <div class="step row conclusive">
            <div class="col-lg-12 centered">
              <p class="button">
                <%= link_to 'Empieza a recolectar', participa_donando_path, class: 'btn btn-primary btn-primary-lg' %>
              </p>
              <p class="mini-title">y gana dinero!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/privacy_note.html.erb
<%= content_for :navbar_menu_items do %>
  <%= render 'devise/shared/navbar_items' %>
<% end %>

<div class="container privacy-note login">
	<div class="row">
		
		<div class="col-lg-6 col-lg-offset-3">
			<div class="well bs-component">
				<h3 class="title">Aviso de privacidad</h3>
          <p><b>Identidad y domicilio del responsable</b></p>

          <p>REcyclo.com (en lo sucesivo “Recyclo”), representada por Alejandro E. Cruz Paz con domicilio en Cumbres de Maltrata 162-206 Narvarte Poniente, Del. Benito Juárez, C.P. 03020, México D.F.</p>

          <p><b>Datos personales que recaba Recyclo</b></p>

          <p>Los datos personales que Recyclo recaba tienen como finalidad poner en contacto a recolectores de residuos sólidos y donadores de residuos sólidos registrados en el sitio web recyclo.com, así como ofrecer servicios, productos y aplicaciones relacionadas con el reciclaje de residuos. Para ello, Recyclo recolecta los siguientes datos:</p>
          <div class="list-group">
            <a href="#" class="list-group-item">Nombre y apellido.</a>
            <a href="#" class="list-group-item">Correo o correos electrónicos.</a>
            <a href="#" class="list-group-item">Ubicación.</a>
            <a href="#" class="list-group-item">Fotografía personal.</a>
            <a href="#" class="list-group-item">Datos de tarjetas bancarias de crédito o débito.</a>
          </div>

        <p>En caso de no contar con esta información Recyclo no estaría en posibilidad de ofrecer sus servicios a recolectores de residuos y donadores de residuos.

        Las cookies son archivos de texto que son descargados automáticamente y almacenados en el disco duro del equipo de cómputo del usuario al navegar en una página de Internet específica, que permiten recordar al servidor de Internet algunos datos sobre este usuario, entre ellos, sus preferencias para la visualización de las páginas en ese servidor, nombre y contraseña. 

        Por su parte, las web beacons son imágenes insertadas en una página de Internet o correo electrónico, que puede ser utilizado para monitorear el comportamiento de un visitante, como almacenar información sobre la dirección IP del usuario, duración del tiempo de interacción en dicha página y el tipo de navegador utilizado, entre otros.</p>

        <p>Le informamos que utilizamos cookies y web beacons para obtener información personal de usted, como la siguiente:</p>

        <div class="list-group">
          <a href="#" class="list-group-item">Su tipo de navegador y sistema operativo.</a>
          <a href="#" class="list-group-item">Las páginas de Internet que visita.</a>
          <a href="#" class="list-group-item">Los vínculos que sigue.</a>
          <a href="#" class="list-group-item">La dirección IP.</a>
          <a href="#" class="list-group-item">El sitio que visitó antes de entrar al nuestro.</a>
        </div>
        
        <p><b>Finalidades del tratamiento de datos personales</b></p>

        <p>Sus datos personales serán utilizados con las siguientes finalidades:</p>
        
        <div class="list-group">
          <a href="#" class="list-group-item">Ponerle en contacto con otros usuarios de Recyclo para generar donaciones o adquisiciones de residuos sólidos y para valorar su desempeño en la plataforma.</a>
          <a href="#" class="list-group-item">Informar de nuevos servicios o productos que Recyclo ponga a disposición del público.</a>
          <a href="#" class="list-group-item">Informar sobre noticias, recordatorios y otras notificaciones relacionadas con la operación de la plataforma.</a>
          <a href="#" class="list-group-item">Generar cobros debidamente autorizados por usted a su tarjeta de crédito o débito.</a>
        </div>
        
        <p><b>Opciones y medios para limitar el uso y divulgación de sus datos personales</b></p>

        <p>
        Usted puede dejar de recibir mensajes por correo electrónico de parte de Recyclo enviando  un correo electrónico a la dirección contacto@recyclo.mx solicitando dejar de recibir correos electrónicos de nuestra parte.

        Los cookies que utilizamos para obtener su información personal se pueden deshabilitar de la siguiente forma:</p>
        
        <div class="list-group">
          <a href="#" class="list-group-item">Ir a la sección de configuración o preferencias en su explorador web.</a>
          <a href="#" class="list-group-item">Ir a la pestaña de privacidad</a>
          <a href="#" class="list-group-item">Seleccionar eliminar cookies de manera individual.</a>
          <a href="#" class="list-group-item">Seleccionar de la lista <i>www.recyclo.mx</i> y dar click en eliminar.</a>
        </div>

        <p><b>Acceso, rectificación, cancelación u oposición al uso de sus datos personales</b></p>

        <p>
        Usted tiene derecho de acceder a sus datos personales que poseemos y a los detalles del tratamiento de los mismos, así como a rectificarlos en caso de ser inexactos o instruirnos a cancelarlos cuando considere que resulten excesivos o innecesarios para las finalidades que justificaron su obtención u oponerse al tratamiento de los mismos para fines específicos.

        Para ejercer estos derechos, favor de ponerse en contacto a través del correo electrónico contacto@recyclo.mx.</p>


        <p><b>Transferencias de datos personales</b></p>

        <p>Recyclo no realiza transferencias de sus datos personales a terceros.</p>

        <p><b>Cambios al aviso de privacidad</b></p>

        <p>Nos reservamos el derecho de efectuar en cualquier momento modificaciones o actualizaciones al presente aviso de privacidad, para la atención de novedades legislativas o jurisprudenciales, políticas internas, nuevos requerimientos para la prestación u ofrecimiento de nuestros servicios o productos y prácticas del mercado.

        Estas modificaciones estarán disponibles al público a través de los siguientes medios: (i) anuncios visibles en nuestros establecimientos o centros de atención a clientes; (ii) trípticos o folletos disponibles en nuestros establecimientos o centros de atención a clientes; (iii) en nuestra página de Internet [www., sección aviso de privacidad]; (iv) o se las haremos llegar al último correo electrónico que nos haya proporcionado. 
        La fecha de la última actualización al presente aviso de privacidad: 10 de marzo de 2015.</p>
        
			</div>
		</div>
	</div>
</div>